---
# vars file for rabbitmq_server
## install rabbitmq-redhat
rabbitmq_distro_packages:
  - rabbitmq-server
rabbitmq_master_node: "{{ hostvars[groups['rabbitmq'][0]]['ansible_hostname'] }}"
rabbitmq_cluster_name: openstack_message_cluster
rabbitmq_server_service: rabbitmq-server
rabbitmq_auth_user: openstack
rabbitmq_auth_password: Jd0Hs5XHmFrJzPTW
rabbitmq_cookie_token: Jd0Hs5XHmFrJzPTW
rabbitmq_plugins:
  - name: rabbitmq_management
    state: enabled