---
#============= Update/Upgrade All Packages
- name: Update apt-get repo and cache
  apt:
    update_cache: yes 
    force_apt_get: yes
    cache_valid_time: 3600

- name: Upgrade all apt packages
  apt: 
    upgrade: dist
    force_apt_get: yes

#============= Config NTP Service
- name: Install NTP
  apt:
    name: ntp
    state: latest
    force_apt_get: yes    

- name: Remove localtime
  command: rm -f /etc/localtime
  args:
    warn: false

- name: Link TimeZone +7
  command: ln -sf /usr/share/zoneinfo/Asia/Ho_Chi_Minh /etc/localtime
  args:
    warn: false

- name: Restart NTP service
  service:
    name: ntp
    state: restarted  
    enabled: yes

#============= Clear cache apt-get repo old when clone VM
# - name: Clear cache apt-get repo old when clone VM
#   command: "{{ item }}"
#   loop:  
#     - apt-get clean
#     - apt-get autoclean
#     - apt-get autoremove
#   args:
#     warn: false

#============= Intall Packages
- name: Install Packages
  apt:
    force_apt_get: yes    
    state: latest
    name:
      - htop
      - iotop
      - atop
      - glances
      - vim
      - telnet
      - traceroute
      - net-tools
      - wget
      - git
      - curl
      - nmap
  ignore_errors: yes

#============= Change color root user to RED
- name: Change color root user
  lineinfile: >
    dest=/root/.bashrc
    line='force_color_prompt=yes'
    line='PS1="\[\e[01;31m\]$PS1\[\e[00m\]"'
    state=present

#============= SSH Configs
# - name: Allow users ssh to server
#   lineinfile: >
#     dest=/etc/ssh/sshd_config
#     line='AllowUsers {{ item.name }}'
#     state=present
#   with_items:
#     - "{{ users }}"
#   when: item.servers and inventory_hostname in item.servers

# - name: restart sshd
#   service: name={{ item }} state=restarted
#   with_items:
#     - sshd
#   ignore_errors: yes
#   become: yes
#   when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

# - name: restart sshd
#   systemd:
#     state: restarted
#     daemon_reload: yes
#     name: sshd
#   ignore_errors: yes
#   become: yes
#   when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

#============= Disable firewall service
# - name: Check if ufw package is installed
#   command: systemctl ufw status
#   args:
#     warn: false
#   register: ufw_installed
#   ignore_errors: true
#   changed_when: true
#   when:
#     - firewall_disable_ufw
#   check_mode: false

- name: Disable the ufw firewall
  service:
    name: ufw
    state: stopped
    enabled: false
  when:
    - ansible_distribution == "Ubuntu"

#============= Install Node Exporter