---
- name: agent_script | Copy User parameters file to zabbix_agentd.d
  become: yes
  copy:
     src={{ item }}
     dest=/etc/zabbix/zabbix_agentd.d/
     mode=0644
     owner=root
     group=root
  with_fileglob:
    - "zabbix_agent_userparameters/*"
  notify: restart zabbix_agent

- name: agent_script | Create zabbix_custom_scripts Directory
  become: yes
  file:
     path={{ zabbix_agent_dir_custom }}
     owner=root
     group=root
     state=directory

- name: agent_script | Copy custom scripts (discovery, ...)
  become: yes
  copy:
     src={{ item }}
     dest={{ zabbix_agent_dir_custom }}
     owner=root
     group=root
     mode=0755
  with_fileglob:
     - "zabbix_custom_scripts/*"
  tags: zabbix_agent
  notify: restart zabbix_agent

- name: agent_script | install package for custom scripts
  become: yes
  yum: name={{ item }} state=present
  with_items: '{{ zabbix_agent_custom_yum }}'
  tags: zabbix_agent
  notify: restart zabbix_agent
