---
- name: zabbix_check_megaraid_sas | copy MegaRAID tool
  become: yes
  copy: >
    src=MegaRAID
    dest=/opt
    mode=0755
    owner=root
    group=root
  when: ansible_os_family == "RedHat"

- name: zabbix_check_megaraid_sas | configure zabbix sudoers file
  become: yes
  template:
    src=agent/zabbix-megaraid-sas-sudoers.j2
    dest=/etc/sudoers.d/zabbix-sudoers
    mode=0640
    owner=root
    group=root
    validate='visudo -cf %s'
  register: zabbixSudo
  when: ansible_os_family == "RedHat"

- name: zabbix_check_megaraid_sas | copy megaraid user parameter
  become: yes
  template:
    src=agent/userparameter_megaraid_sas.conf.j2
    dest=/etc/zabbix/zabbix_agentd.d/userparameter_megaraid_sas.conf
    mode=0644
    owner=root
    group=root
  when: ansible_os_family == "RedHat"
