---
- name: zabbix_check_mpt_sas2 | copy sas2ircu binary file to server
  become: yes
  copy:
    src=sas2ircu
    dest=/usr/sbin/sas2ircu
    mode=0755
    owner=root
    group=root
  when: ansible_os_family == "RedHat"

- name: zabbix_check_mpt_sas2 | copy fusion-mpt sas2 userparameter to server
  become: yes
  template:
    src=agent/userparameter_mpt_sas2.conf.j2
    dest=/etc/zabbix/zabbix_agentd.d/userparameter_mpt_sas2.conf.j2
    mode=0644
    owner=root
    group=root
  when: ansible_os_family == "RedHat"

- name: zabbix_check_mpt_sas2 | configure zabbix sudeors file
  become: yes
  template:
    src=agent/zabbix-mpt-sas2-sudoers.j2
    dest=/etc/sudoers.d/zabbix-sudoers
    mode=0640
    owner=root
    group=root
    validate='visudo -cf %s'
  register: zabbixSudo
  when: ansible_os_family == "RedHat"

- name: zabbix_check_mpt_sas2 | copy check_fusion_mpt_sas2_raid.sh script to script directory
  become: yes
  copy:
    src=check_fusion_mpt_sas2_raid.sh
    dest=/etc/zabbix/scripts/check_fusion_mpt_sas2_raid.sh
    mode=0755
    owner=root
    group=root
  notify: restart nrpe
