---
- name: zabbix_proxy | Import initial schema
  shell: zcat {{ zabbix_proxy_sql_file }} | mysql -uroot {{ zabbix_proxy_db_name }}
  register: mysql_schema
  changed_when: "mysql_schema.rc == 0"
  failed_when: "mysql_schema.rc != 0 and 'already exists' not in mysql_schema.stderr"
  tags: mysql_server
