---
- hosts: all
  strategy: free
  gather_facts: yes
  become: yes
  roles:
      - { role: test, tags: test }
      - { role: docker, tags: docker }
      - { role: ntp, tags: ntp }
      - { role: packages, tags: packages }
      - { role: firewall, tags: firewall }
      - { role: users, tags: users }
      - { role: common, tags: common }
      - { role: common_k8s, tags: commonk8s }
      - { role: terraform, tags: terraform }
      - { role: vault, tags: vault }
      - { role: selinux, tags: selinux }
      - { role: letsencrypt, tags: ssl }

      - { role: kafka, tags: kafka }
      - { role: consul, tags: consul }
      - { role: redis, tags: redis }    

#=== ELK
      - { role: elk, tags: elk }
      - { role: elasticsearch, tags: elastic }

#=== HAProxy_Keepalived
      - { role: haproxy, tags: haproxy }
      - { role: keepalived, tags: keepalived }

#=== OpenVPN
      - { role: openvpn_server, tags: openvpn_server }
      - { role: openvpn_client, tags: openvpn_client }

#=== DBs
      - { role: mongodb, tags: mongodb }
      - { role: postgres, tags: postgres }
      - { role: mysql, tags: mysql }

#=== Git-CE, git-runner
      - { role: gitlab-runner, tags: gitlab-runner }
      - { role: gitlab-ce, tags: gitlab-ce }


#=== Prometheus/Grafana with Exporters
      - { role: prometheus, tags: prometheus }
      - { role: grafana, tags: grafana }
      - { role: grafana_loki, tags: grafana_loki }
      - { role: node_exporter, tags: node_exporter }     
      - { role: alertmanager, tags: alertmanager }
      - { role: blackbox_exporter, tags: blackbox_exporter }
      - { role: snmp_exporter, tags: snmp_exporter }
      - { role: mongodb_exporter, tags: mongodb_exporter }
      - { role: bind_exporter, tags: bind_exporter }
#===

      - { role: bind_dns, tags: bind_dns }
      - { role: snmp, tags: snmp }

      - { role: firewallcsf, tags: firewallcsf }