---
- hosts: 192.168.10.212
  become: true
  remote_user: root
  roles:
    - role: nginxinc.nginx
  vars:
    nginx_http_template_enable: true
    nginx_http_template:
      default:
        template_file: http/ssl-vhost.conf.j2
        conf_file_name: ssl-cms.phimhub.aphim.co
        conf_file_location: /etc/nginx/conf.d/
        port: 443
        server_name: cms.phimhub.aphim.co
        root: /home/www/cms.phimhub.aphim.co/public_html
        error_log: /var/log/nginx/xapi.aphim.error.log
        access_log: /var/log/nginx/xapi.aphim.access.log main
        index: index.php
        ssl: on
        ssl_protocols: TLSv1 TLSv1.1 TLSv1.2
        ssl_certificate: /etc/letsencrypt/live/cms.phimhub.aphim.co/fullchain.pem
        ssl_certificate_key: /etc/letsencrypt/live/cms.phimhub.aphim.co/privkey.pem
        ssl_ciphers: ALL:!ADH:!EXPORT:!SSLv2:RC4+RSA:+HIGH:+MEDIUM:+LOW
        ssl_prefer_server_ciphers: on
        add_header: Front-End-Https on
        ssl_session_timeout: 10m
        web_server:
          location:
            name: /uploads/
            name2: ~ .*\.(php)?$
            deny: all
          location_2:
            name: /.well-known/
          location_3:
            name: ~ /*/(.git|.svn)/
            return: 404
          
          location_4:
            name: ~ /*/.gitignore
            return: 404
          location_5:
            name: /
            proxy_pass: http://backend1
            include: /usr/local/nginx/conf.d/nginx_proxy
        if:
          location:
            name: ($request_method !~ ^(GET|HEAD|POST|PUT)$ )
            return: 444
        include: /usr/local/nginx/conf.d/set_real_ips
        gzip: on
        gzip_http_version: 1.1
        gzip_comp_level: 9
        gzip_proxied: any
        gzip_min_length:  1100
        gzip_buffers: 16 8k
        gzip_types: text/plain  text/css application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript
        gzip_vary: on
        gzip_disable: "MSIE [1-6].(?!.*SV1)"

