---
- hosts: 192.168.10.212
  become: true
  remote_user: root
  roles:
    - role: nginxinc.nginx
  vars:
    nginx_http_template_enable: true
    nginx_http_template:
      default:
        template_file: stream/upstream.conf.j2
        conf_file_name: upstream.conf
        conf_file_location: /etc/nginx/conf.d/
        upstreams:
          upstream_1:
            name: appvn-front
            server1: 10.0.0.26:89 weight=3 max_fails=3  fail_timeout=30s
            server2: 10.0.0.27:88 weight=3 max_fails=3  fail_timeout=30s
            keepalive: 32
          upstream_2:
            name: vault-appvn-net
            server1: 10.0.0.8:8200 weight=3 max_fails=3  fail_timeout=30s
            keepalive: 32
          upstream_3: 
            name: vi-appvn-front
            server1: 10.0.0.26:88 weight=3 max_fails=3  fail_timeout=30s
            server2: 10.0.0.27:88 weight=3 max_fails=3  fail_timeout=30s
            keepalive: 32
          upstream_4:
            name: dlapk-io
            server1: 10.0.0.26:88 weight=3 max_fails=3  fail_timeout=30s
            #server2:
            keepalive: 32
          upstream_5:
            name: abooks-cms
            server1: 10.0.0.22:88 weight=3 max_fails=3  fail_timeout=30s
            #server2:
            keepalive: 32
          upstream_6:
            name: cms1-appvn-com
            server1: 10.0.0.22:88 weight=3 max_fails=3  fail_timeout=30s
            #server2: 
            keepalive: 32
          upstream_7:
            name: congtruyen
            server1: 10.0.0.26:88 weight=3 max_fails=3  fail_timeout=30s
            server2: 10.0.0.27:88 weight=3 max_fails=3  fail_timeout=30s
            keepalive: 32
          upstream_8:
            name: aphim-web
            #server1: 
            server2: 10.0.0.22:88 weight=3 max_fails=3  fail_timeout=30s
            keepalive: 32
          upstream_9:
            name: api-aphim
            server1: 10.0.0.22:88 weight=3 max_fails=3  fail_timeout=30s
            server2: 10.0.0.25:88 weight=3 max_fails=3  fail_timeout=30s
            keepalive: 32
          upstream_10:
            name: api-aphim-v2
            server1: 10.0.0.26:88 weight=3 max_fails=3  fail_timeout=30s backup
            server2: 10.0.0.27:88 weight=3 max_fails=3  fail_timeout=30s
            keepalive: 32
          upstream_11:
            name: abooks
            server1: 10.0.0.22:88 weight=3 max_fails=3  fail_timeout=30s
            server2: 10.0.0.25:88 weight=3 max_fails=3  fail_timeout=30s backup
            keepalive: 32
          upstream_12:
            name: api-aphim-dev
            server1: 10.0.0.22:88 weight=3 max_fails=3  fail_timeout=30s
            #server2:
            keepalive: 32
          upstream_13:
            name: appvn
            ip_hash: true
            server1: 10.0.0.22:88 weight=3 max_fails=3  fail_timeout=30s
            #server2:
            keepalive: 32
          upstream_14:
            name: aphimnews
            ip_hash: true
            server1: 43.239.220.253:80 weight=3 max_fails=3  fail_timeout=30s
            #server2:
            keepalive: 32
          upstream_15:
            name: appvn_update_code
            server1: 10.0.0.22:5000
            #server2: 
            keepalive:
          upstream_16:
            name: cms_en_appvn
            server1: 10.0.0.22:1337
            #server2:
            keepalive:
          upstream_17:
            name: xms-aphim
            ip_hash: true
            server1: 10.0.0.22:88 weight=3 max_fails=3  fail_timeout=30s
            #server2: 
            keepalive: 32
          upstream_18:
            name: backend1
            ip_hash: true
            server1: 10.0.0.22:88 weight=3 max_fails=3  fail_timeout=30s
            #server2:
            keepalive: 32
          upstream_19:
            name: cms-congtruyen
            ip_hash: true
            server1: 10.0.0.22:88 weight=3 max_fails=3  fail_timeout=30s
            server2: 10.0.0.25:88 weight=3 max_fails=3  fail_timeout=30s
            keepalive: 32
          upstream_20:
            name: v2-aphim
            ip_hash: true
            server1: 10.0.0.22:88 weight=3 max_fails=3  fail_timeout=30s
            #server2: 
            keepalive: 32
          upstream_21:
            name: api-congtruyen
            ip_hash: true
            server1: 10.0.0.22:88 weight=3 max_fails=3  fail_timeout=30s
            server2: 10.0.0.25:88 weight=3 max_fails=3  fail_timeout=30s
            keepalive: 32
          upstream_22:
            name: api-appvn-net
            server1: 10.0.0.22:88 weight=3 max_fails=3  fail_timeout=30s backup
            server2: 10.0.0.25:88 weight=3 max_fails=3  fail_timeout=30s
            keepalive: 32
          upstream_23:
            name: insai-appvn
            server1: 10.0.0.22:88 weight=3 max_fails=3  fail_timeout=30s
            server2: 10.0.0.25:88 weight=3 max_fails=3  fail_timeout=30s
            keepalive: 32
          upstream_24: 
            name: apptoko-com 
            server1: 10.0.0.27:88 weight=3 max_fails=3  fail_timeout=30s
            server2: 10.0.0.26:88 weight=3 max_fails=3  fail_timeout=30s
            keepalive: 32
          upstream_25:
            name: playtoko-com
            ip_hash: true
            #server1: 
            server2: 10.0.0.25:88 weight=3 max_fails=3  fail_timeout=30s
            keepalive: 32
          upstream_26:
            name: api-9book-org
            server1: 10.0.0.26:88 weight=3 max_fails=3  fail_timeout=30s
            #server2: 
            keepalive: 32
          upstream_27:
            name: cms-9book-org
            server1: 10.0.0.26:88 weight=3 max_fails=3  fail_timeout=30s
            #server2: 
            keepalive: 32

