---
- hosts: 192.168.10.222
  become: true
  remote_user: root
  roles:
    - role: nginxinc.nginx
  vars:
    nginx_http_template_enable: true
    nginx_http_template:
      default:
        template_file: http/vhost.conf.j2
        conf_file_name: testvhost.conf
        conf_file_location: /etc/nginx/conf.d/
        port: 80
        server_name: xxx.apptoko.com
        access_log: /var/log/nginx/xxx.apptoko.com.access.log main
        error_log: /var/log/nginx/xxx.apptoko.com.error.log error
        pid: /var/run/nginx.pid
        index: index.html
        root: /home/www/xxx.apptoko.com/public_html
        add_header: Front-End-Https on
        real_ip_header: X-Forwarded-For
        port_in_redirect: off
        rewrite: ^/phim/(.*)/play https://aphim.co/phim/$1/ permanent
        autoindex: false
        client_max_body_size: 20m
        include: /usr/local/nginx/conf.d/set_real_ips
        error_page: 502 /baotri.html
        web_server:
          location_1:
            name: = /baotri.html
            root: /home/www/appvn.com/public_html
            internal: true
          location_2:
            name: ~ /*/(.git|.svn)/
            return: 404
          location_3:
            name: ~ /*/(.git|.svn)/
            return: 404
            add_header: Pragma "public"
            access_log: off
            expires: max
            tcp_nodelay: off
            open_file_cache: max=3000 inactive=120s
            open_file_cache_valid: 45s
            open_file_cache_min_uses: 2
            open_file_cache_errors: off
            log_not_found: off
            break : true
          location_4:
            name: ~ /*/.gitignore
            return: 404
          location_5:
            name: ^~ /uploads/
            name2: ~ .*\.(php)?$
            deny2: all
        if:
          locations:
            default:
              location: ($http_cf_visitor ~ '{"scheme":"http"}')
              return: 301 https://$server_name$request_uri
        fastcgi:
          location: \
          pass: unix:/var/run/php_fpm.sock
          index: index.php
          include: fastcgi_params
          param: SCRIPT_FILENAME $document_root$fastcgi_script_name
          split_path_info: ^(.+\.php)(.*)$
          PATH_INFO: $fastcgi_path_info
          PATH_TRANSLATED: $document_root$fastcgi_path_info
          connect_timeout: 180
          send_timeout: 180
          read_timeout: 180
          buffer_size: 128k
          buffers: 4 256k
          busy_buffers_size: 256k
          temp_file_write_size: 256k
          intercept_errors: true
          GEOIP_COUNTRY_CODE: $geoip_country_code
          GEOIP_COUNTRY_CODE3: $geoip_country_code3
          GEOIP_COUNTRY_NAME: $geoip_country_name
          GEOIP_CITY_COUNTRY_CODE: $geoip_city_country_code
          GEOIP_CITY_COUNTRY_CODE3: $geoip_city_country_code3
          GEOIP_CITY_COUNTRY_NAME: $geoip_city_country_name
          GEOIP_REGION: $geoip_region
          GEOIP_CITY: $geoip_city
          GEOIP_POSTAL_CODE: $geoip_postal_code
          GEOIP_CITY_CONTINENT_CODE: $geoip_city_continent_code
          GEOIP_LATITUDE: $geoip_latitude
          GEOIP_LONGITUDE: $geoip_longitude
        proxy:
          locations:
            default:
              location: \
              proxy_cache: off
              proxy_pass: http://xxx-apptoko-com
              include: /usr/local/nginx/conf.d/nginx_proxy
              proxy_cache_methods: GET HEAD
              proxy_cache_valid: 200 30m
              expires: 30m
              proxy_cache_valid2: 301 2h
              proxy_cache_valid3: 400 403 404 1m
              proxy_no_cache: $cookie_PHPSESSID
              proxy_cache_bypass: $cookie_PHPSESSID
              proxy_cache_key: "$scheme$host$request_uri"
        gzip: on
        gzip_http_version: 1.1
        gzip_comp_level: 9
        gzip_proxied: any
        gzip_min_length:  1100
        gzip_buffers: 16 8k
        gzip_types: text/plain  text/css application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript
        gzip_vary: on
        gzip_disable: "MSIE [1-6].(?!.*SV1)"
