---
# - include: "{{ ansible_os_family }}.yml"

- name: Disable SELinux
  include_role:
    name: selinux

#============= Clear cache apt-get repo old when clone VM
- name: Clear cache apt-get repo old when clone VM
  command: "{{ item }}"
  loop:  
    - apt-get clean
    - apt-get autoclean
    - apt-get autoremove
  args:
    warn: false


#============= Update/Upgrade All Packages
- name: Update apt-get repo and cache
  apt:
    update_cache: yes 
    force_apt_get: yes
    cache_valid_time: 3600

- name: Upgrade all apt packages
  apt: 
    upgrade: dist
    force_apt_get: yes


#============= Config VMs
- name: Install Necessary Packages
  include_role:
    name: packages

- name: NTP Service
  include_role:
    name: ntp

- name: SNMP Service
  include_role:
    name: snmp

- name: Firewall Service | OFF
  include_role:
    name: firewall

- name: Disable the systemd-resolved | Ubuntu
  service:
    name: systemd-resolved
    state: stopped
    enabled: false
  when: ansible_os_family == "Debian"

- name: SSHD Service
  include_role:
    name: users

# - name: Docker_docker-compose Service
#   include_role:
#     name: docker

- name: SSH Login Alert
  include_role:
    name: ssh_login_alert_2

    
#============= Install Exporters for Prometheus Monitor
- name: Node Exporter Service
  include_role:
    name: node_exporter

- name: Blackbox Exporter Service for ICMP/SSL Monitor
  include_role:
    name: blackbox_exporter

- name: SNMP Exporter Service
  include_role:
    name: snmp_exporter