---
- name: Install Necessary Packages
  apt:
    name: 
      - apt-transport-https
      - software-properties-common
      - wget
    force_apt_get: yes      
    state: present       

- name: Add Grafana Key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana repository for stable releases
  apt_repository: 
    repo: deb https://packages.grafana.com/enterprise/deb stable main
    state: present

- name: Install Grafana latest Enterprise edition
  apt: 
    name: 
      - grafana-enterprise
    update_cache: yes
    force_apt_get: yes      
    state: present

- name: Copy grafana.ini file
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini

- name: Start Grafana
  systemd:
    name: grafana-server
    state: started
    daemon_reload: yes
    enabled: yes

- name: Add Prometheus Data Source
  grafana_datasource:
    name: "{{ data_source.name }}"
    grafana_url: "{{ grafana_url }}"
    grafana_user: "{{ grafana_user }}"
    grafana_password: "{{ grafana_password }}"
    ds_type: "{{ data_source.ds_type }}"
    url: "{{ data_source.url }}"
    state: present
  with_items: "{{ data_source }}"


# - name: Allow intra net access to grafana
#   iptables:
#     chain: INPUT
#     protocol: tcp
#     source: 10.0.0.0/8
#     destination_port: '3000'
#     jump: ACCEPT

# - name: Save iptables rules to /etc/sysconfig/iptables
#   lineinfile:
#     path: /etc/sysconfig/iptables
#     line: '-A INPUT -s 10.0.0.0/8 -p tcp -m tcp --dport 3000 -j ACCEPT'