---
- name: Install python-apt Package
  apt:
    name: 
      - python-apt
    state: present         
    update_cache: yes
    force_apt_get: yes  

- name: Uninstall Docker Old
  apt:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine  
    state: absent
    force_apt_get: yes

- name: Install prerequisites for Docker repository
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
    state: present        
    update_cache: yes
    force_apt_get: yes

- name: Add Docker GPG key
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

- name: Install Docker CE
  apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present         
    update_cache: yes
    force_apt_get: yes      


#===== Docker Compose ====
- name: Install prerequisites for docker-compose
  apt:
    name: 
      - python3-pip
      - python3-setuptools
      - virtualenv
    state: present       
    force_apt_get: yes

- name: Install docker-compose
  get_url: 
    url : https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: "{{ docker_compose_path }}"
    mode: 'u+x,g+x'

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Check status of docker service
  service_facts:
  register: service_state

- debug:
    var: service_state.ansible_facts.services["docker.service"].state