---
# Variables for Node_Exporter

node_exporter_version: 1.0.1
node_exporter_src_dir: /usr/local/bin
node_exporter_group: node_exporter
node_exporter_user: node_exporter


#===> ansible_architecture
go_arch_map:
  i386: '386'
  x86_64: 'amd64'
  aarch64: 'arm64'
  armv7l: 'armv7'
  armv6l: 'armv6'

go_arch: "{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}"
#===> ansible_architecture