---
- name: Disable selinux temporary
  command: setenforce 0
  ignore_errors: True

- name: Disable selinux after reboot
  selinux:
    state: disabled

- name: Install Java
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - java-1.8.0-openjdk
    - ntp

- name: Install Elastic search
  yum: 
    name: 'https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ version }}.rpm'
    state: present

- name: Update file config elastichsearch
  template: 
    src: elasticsearch.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    mode: 0644

- name: Optimize limits.conf when enable bootstrap.memory_lock
  blockinfile:
    path: /etc/security/limits.conf
    content: |
      *   soft    memlock         unlimited
      *   hard    memlock         unlimited
      *   soft    nofile          65536
      *   hard    nofile          65536

- name: Enable ip_conntrack
  shell: modprobe ip_conntrack

- name: Optimize sysctl.conf
  template: 
    src: sysctl.j2
    dest: /etc/sysctl.conf

- name: Apply sysctl config
  shell: sysctl -p

- name: Optimize sysconfig for elasticsearch
  blockinfile:
    path: /etc/sysconfig/elasticsearch
    content: |
      ES_JAVA_OPTS="-Xms{{ (ansible_memtotal_mb * 0.0006)|int }}g -Xmx{{ (ansible_memtotal_mb * 0.0006)|int }}g" 
      MAX_LOCKED_MEMORY=unlimited

- name: Add file serivice management for enable bootstrap.memory_lock
  blockinfile: 
    path: /usr/lib/systemd/system/elasticsearch.service
    insertafter: 'LimitNOFILE=65536'
    content: |
      LimitMEMLOCK=infinity

- name: Reload systemd to reread configs
  systemd: 
    daemon_reload: yes

- name: Edit /etc/elasticsearch/jvm.options JVM max
  lineinfile:
    path: /etc/elasticsearch/jvm.options
    state: present
    regexp: '^-Xms'
    insertafter: '^-Xms'
    line: '-Xms{{ (ansible_memtotal_mb * 0.0006)|int }}g'
     
- name: Edit /etc/elasticsearch/jvm.options JVM min
  lineinfile:
    path: /etc/elasticsearch/jvm.options
    state: present
    regexp: '^-Xmx'
    insertafter: '^-Xmx'
    line: '-Xmx{{ (ansible_memtotal_mb * 0.0006)|int }}g'

- name: Create data folder
  file:
    path: "{{ item }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: 0744
  with_items:
    - "{{ data_dir }}"
    - "{{ log_dir }}"

- name: Start Elasticsearch Service
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - elasticsearch
    - ntpd

- name: Install kibana on Client node
  yum:
    name: 'https://artifacts.elastic.co/downloads/kibana/kibana-{{ version }}-x86_64.rpm'
    state: present
  when: roles == 'client'

- name: Config kibana
  template: 
    src: kibana.j2
    dest: /etc/kibana/kibana.yml
    backup: yes
  when: roles == 'client'

- name: Start Kibana Service
  systemd:
    name: kibana
    state: restarted
    enabled: yes
  when: roles == 'client'