---

xtrabackup_version: 24  # 2.4
#xtrabackup_version: 80  # 8.0

master_ip: 192.168.10.81
slave_ip: 192.168.10.82
user_root: 
  name: root
  pass:

db_name: hanhnn
collation: utf8_general_ci
encoding: utf8

hanhnn_user: hanhnn
hanhnn_pass: 123@hanhsu

config_file_path: /etc/my.cnf.d/server.cnf

replication_user:
  name: repl
  pass: repl123@

# Replication settings (replication is only enabled if master/user have values).
mysql_server_id: "1"
mysql_max_binlog_size: "100M"
mysql_binlog_format: "ROW"
mysql_expire_logs_days: "10"
mysql_replication_role: ''
mysql_replication_master: ''
# Same keys as `mysql_users` above.



mysql_replication_user: replica
mysql_replication_password: replica123@

#==============
mariadb_upstream_version: 10.5
mariadb_apt_keys: ['0xcbcb082a1bb943db', '0xF1656F24C74CD1D8']
mariadb_distribution: '{{ ansible_local.core.distribution
                         if (ansible_local|d() and ansible_local.core|d() and
                             ansible_local.core.distribution|d())
                         else ansible_distribution }}'
mariadb_distribution_release: '{{ ansible_local.core.distribution_release
                                 if (ansible_local|d() and ansible_local.core|d() and
                                     ansible_local.core.distribution_release|d())
                                 else ansible_distribution_release }}'                         
mariadb_repository: deb [arch=amd64,arm64,ppc64el] http://mariadb.mirror.liquidtelecom.com/repo/{{ mariadb_upstream_version }}/{{ mariadb_distribution | lower }} {{ ansible_distribution_release }} main

#deb [arch=amd64,arm64,ppc64el] http://mariadb.mirror.liquidtelecom.com/repo/{{ mariadb_upstream_version }}/{{ mariadb_distribution | lower }} $(lsb_release -cs) main
