---

- name: Disable selinux temporary
  command: setenforce 0
  ignore_errors: True

- name: Disable selinux after reboot
  selinux:
    state: disabled

- name: Import signing key for RabbitMQ
  rpm_key:
    state: present
    key: https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc

- name: Creat RabbitMQ Repo
  template:
    src: rabbitmq.repo.j2
    dest: /etc/yum.repos.d/rabbitmq.repo
    mode: 0644

- name: Install Epel repo, Erlang-solutions
  yum:
    name:
      - epel-release
      - http://packages.erlang-solutions.com/erlang-solutions-1.0-1.noarch.rpm
    state: installed

- name: Install Erlang, Rabbitmq-server latest version
  yum:
    name:
      - erlang
      - rabbitmq-server
    state: installed