---
- name: restart thanos query
  listen:
    - restart thanos-query
  become: true
  systemd:
    daemon_reload: true
    name: thanos-query
    state: restarted
    enabled: yes

- name: reload thanos-query
  listen:
    - reload thanos-query
  become: true
  systemd:
    name: thanos-query
    state: reloaded