---
- name: Update DNS to Kdata DNS server
  template :
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == "RedHat"
  sudo: yes
