---

- name: Creates directory for archiving purposes
  file:
    path: /var/lib/pgsql/{{ postgresql_version }}/archive
    state: directory
    owner: postgres
    group: postgres
    mode: 0700
  when: roles == "master"    
  tags: 
    - psql_repl


#=============== Configure PostgreSQL for MASTER
- name: Configure PostgreSQL for MASTER
  template:
    src: postgresql.conf_master.j2
    dest: "/var/lib/pgsql/{{ postgresql_version }}/data/postgresql.conf"
    owner: postgres
    group: postgres
    mode: 0640
  when: roles == "master"    
  tags: 
    - psql_repl

- name: Configure pg_hba.conf for MASTER
  template:
    src: pg_hba.conf.j2
    dest: "{{ postgresql_conf_dir }}/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: 0640
  when: roles == "master"    
  tags: 
    - psql_repl

#=============== Configure PostgreSQL for SLAVE
- name: Configure PostgreSQL for SLAVE
  template:
    src: postgresql.conf_slave.j2
    dest: "/var/lib/pgsql/{{ postgresql_version }}/data/postgresql.conf"
    owner: postgres
    group: postgres
    mode: 0640
  when: roles == "slave"    
  tags: 
    - psql_repl    

- name: Configure pg_hba.conf for SLAVE
  template:
    src: pg_hba.conf.j2
    dest: "{{ postgresql_conf_dir }}/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: 0640
  when: roles == "slave"    
  tags: 
    - psql_repl
#==============================================

- name: Restart Postgres Service
  service:
    name: postgresql-{{ postgresql_version }}
    state: restarted
  when: roles == "master"    
  tags: 
    - psql_repl

- name: Create replication user account
  become: yes
  become_user: "{{ postgresql_admin_user }}"
  postgresql_user:
    name: "{{ postgresql_replication_user.name }}"
    password: "{{ postgresql_replication_user.pass }}"
    role_attr_flags: "{{ role_attr_flags_replication }}"
  when: roles == "master"    
  tags: 
    - psql_repl    