---
- name: Install Necessary Packages | Ubuntu
  apt:
    force_apt_get: yes    
    state: latest
    name:
      - jq
  ignore_errors: yes
  when: ansible_os_family == "Debian"

- name: Install Necessary Packages | CentOS
  yum:
    name:
      - jq   
    state: latest
  when: ansible_os_family == 'RedHat'

- name: Delete file ssh_login_alert.sh OLD
  file:
    path: /etc/profile.d/ssh_login_alert.sh
    state: absent

- name: Copy ssh_login_alert.sh to server
  template:
    src: ssh_login_alert.sh.j2
    dest: /etc/profile.d/ssh_login_alert.sh