---
- name: Create the directories for site specific configurations
  file: path={{nginx_conf_dir}}/{{ item }} state=directory owner=root group={{nginx_group}} mode=0755
  with_items:
    - "conf.d/sites-available"
    - "conf.d/sites-enabled"
    - "conf.d/params"
    - "conf.d"
  #tags: [configuration,nginx]

- name: Ensure log directory exist
  file: path={{ nginx_log_dir }} state=directory owner={{nginx_user}} group={{nginx_group}} mode=0755
  #tags: [configuration,nginx]

- name: Ensure ngx_proxy_cache_path directory exist
  file: path={{ ngx_proxy_cache_path }} state=directory owner={{nginx_user}} group={{nginx_group}} mode=0755
  #tags: [configuration,nginx]
