---

- name: list users
  shell: "source /root/admin-openrc && openstack user list"
  register: ulist
- name: setup service neutron
  block:
    - name: Create the neutron user
      shell: "source /root/admin-openrc && openstack user create --domain default --password {{ neutron_user_password }} neutron"
    - name: Add the admin role to the neutron user
      shell: "source /root/admin-openrc && openstack role add --project service --user neutron admin"
    - name: Create the neutron service entity
      shell: "source /root/admin-openrc && openstack service create --name neutron --description 'OpenStack Networking' network"
    - name: Create the Networking service API endpoints
      shell: "source /root/admin-openrc && openstack endpoint create --region RegionOne network {{ item }} http://{{ internal_vip_address|default(groups['controller'][0]) }}:9696"
      with_items:
        - internal
        - public
        - admin
  when: not ansible_check_mode and ulist.stdout.find("neutron") < 0
