---
- name: Restart glance-api
  systemd:
    name: "openstack-glance-api"
    state: "restarted"
  register: glance_api_restart
  until: glance_api_restart is success
  retries: 5
  delay: 2

- name: Restart glance-registry
  systemd:
    name: " openstack-glance-registry"
    state: "restarted"
  register: glance_registry_restart
  until: glance_registry_restart is success
  retries: 5
  delay: 2