---
- name: Create the node_exporter group
  group:
    name: "{{ node_exporter_group }}"
    state: present
    system: true

- name: Create the node_exporter user
  user:
    name: "{{ node_exporter_user }}"
    groups: "{{ node_exporter_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: /

- name: Download & Decompress Node Exporter source file to /tmp
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch }}.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy binary to "{{ node_exporter_src_dir }}"
  copy:
    src: /tmp/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch }}/node_exporter
    dest: "{{ node_exporter_src_dir }}"
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    mode: 0755
    remote_src: yes

- name: Create systemd service file
  template: 
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: 0755

- name: Reload systemd to reread configs
  systemd: 
    daemon_reload: yes
  when: ansible_service_mgr == "systemd"

- name: Restart Node Exporter Service
  service:
    name: node_exporter
    state: restarted
    enabled: true