- name: Add epel repository
  yum:
    name: "{{ epel_url }}"
    state: present
  when: ansible_os_family == "RedHat"

- name: Add epel repository signing key
  rpm_key:
    key: "{{ epel_key }}"
  when: ansible_os_family == "RedHat"

- name: Install rkhunter
  package:
    name: rkhunter
    state: present