---

- name: SSH | Create folder contain sshkey
  file:
    path: "{{ project_dir_runner }}"
    state: directory
    mode: 0755
  when: roles == "runner"

- name: SSH | Copy key file to Runner
  copy:
    src: "{{ item }}"
    dest: "{{ project_dir_runner }}"
    owner: root
    group: root
    mode: 0400
  with_items:
  - /tmp/id_rsa
  - /tmp/id_rsa.pub
  when: roles == "runner"

- name: SSH | Copy key file to Backend
  copy:
    src: /tmp/id_rsa.pub        
    dest: /tmp/id_rsa.pub
    mode: 0644
  when: roles == "backend"

- name: SSH | Add public key to Web Backend
  shell: | 
    cat /tmp/id_rsa.pub >> /home/deploy/.ssh/authorized_keys
    rm -rf /tmp/id_rsa.pub
  when: roles == "backend"

- name: SSH | Change mode for authorized_keys
  file:
    path: /home/deploy/.ssh/authorized_keys
    owner: deploy
    group: deploy
    mode: 0644
  when: roles == "backend"
