---

- name: Copy script check TCP
  template:
    src=json_item_tcp.j2
    dest=/etc/zabbix/scripts/json_item_tcp.sh
    mode=0755

- name: Copy config check TCP
  template:
    src=userparamets_tcp.j2
    dest=/etc/zabbix/zabbix_agentd.d/userparameter_tcp.conf
    mode=0644
