---

- name: Add Elasticsearch GPG key
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Logstash repository
  template:
    src: logstash.repo_redhat.j2
    dest: /etc/yum.repos.d/logstash.repo
    mode: 0644

- name: Install Logstash v{{ logstash_version }}
  package:
    name: logstash
    state: present

- name: Ensure Logstash is started and enabled at boot.
  service:
    name: logstash
    state: started
    enabled: true