---

- name: Edit /etc/elasticsearch/jvm.options JVM max for Xms
  lineinfile:
    path: /etc/elasticsearch/jvm.options
    state: present
    regexp: '^-Xms'
    insertafter: '^-Xms'
    line: '-Xms{{ (ansible_memtotal_mb * 0.0006)|int }}g'

- name: Edit /etc/elasticsearch/jvm.options JVM max for Xmx
  lineinfile:
    path: /etc/elasticsearch/jvm.options
    state: present
    regexp: '^-Xmx'
    insertafter: '^-Xmx'
    line: '-Xmx{{ (ansible_memtotal_mb * 0.0006)|int }}g'