---

- name: Install elasticsearch | Debian
  include: elasticsearch_debian.yml  

- name: Config elasticsearch
  include: elasticsearch_config.yml


# - name: Make sure elasticsearch is started
#   service: 
#     name: elasticsearch
#     state: started
#     enabled: yes