---

# - name: include java.yml
#   include: java.yml


# - name: include elasticsearch_debian.yml 
#   include: elasticsearch_debian.yml  

# - name: include elasticsearch_config.yml
#   include: elasticsearch_config.yml


# - name: Make sure elasticsearch is started
#   service: 
#     name: elasticsearch
#     state: started
#     enabled: yes

- name: Install Packages
  apt:
    name:
      - apt-transport-https
    state: present
    update_cache: yes

- name: get apt repo key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: install apt repo
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present
    filename: elastic-7.x.list
    update_cache: yes


- name: install java
  apt:
    name:       
      - default-jdk
    state: present
    update_cache: yes

- name: install elasticsearch
  apt:
    name: elasticsearch
    state: present
    update_cache: yes

- name: Reload systemd to reread configs
  command: systemctl daemon-reload

- name: enable service elasticsearch and ensure it is not masked
  systemd:
    name: elasticsearch
    enabled: yes
    masked: no

- name: ensure elasticsearch is running
  systemd: 
    state: started
    name: elasticsearch