---

- name: Install elasticsearch | Debian
  include: Debian.yml  
  when: ansible_os_family == 'Debian'

- name: Install elasticsearch | Redhat
  include: RedHat.yml  
  when: ansible_os_family == 'RedHat'

- name: System Configuration
  include: config.yml