- name: Create admin user
  mongodb_user:
    database: admin
    name: "{{ mongo.user }}"
    password: "{{ mongo.password }}"
    roles:
      - db: admin
        role: root
    state: present
  when: primary and primary is defined

- name: Enable authentication in default config file
  lineinfile:
    path: "/etc/default/mongod"
    regexp: "^OPTIONS="
    line: 'OPTIONS="--auth --config /etc/mongod.conf"'
    backrefs: Yes

- name: Create Folder keyfile
  file:
    path: /etc/mongod
    state: directory

- name: Create keyfile
  shell: "openssl rand -base64 756 > {{ mongo.keyfile }}"
  args:
    creates: "{{ mongo.keyfile }}"

- name: Change permission for keyfile
  file:
    path: "{{ mongo.keyfile }}"
    mode: 0400
    owner: mongod
    group: mongod

- name: Restart mongodb service
  systemd:
    name: mongod
    state: restarted
    enabled: Yes
    daemon_reload: Yes
  register: mongodb_service

- name: Disk tuning for mongodb
  shell: ionice -c2 -n0 -p `pgrep mongod`
  args:
    executable: /bin/bash
  when: mongodb_service is succeeded