- name: Install pip
  apt:
    name: python3-pip
    state: present
    update_cache: yes
    install_recommends: no
    force_apt_get: yes

- name: Install pymongo module
  pip:
    name: pymongo

- name: Add percona mongodb signing key
  copy:
    src: percona-keyring.gpg
    dest: /etc/apt/trusted.gpg.d/
    mode: 0644

- name: Add percona mongodb repository
  apt_repository:
    repo: deb [arch=amd64] http://repo.percona.com/psmdb-42/apt {{ ansible_distribution_release }} main
    state: present
    filename: percona-psmdb-42-release

- name: Install percona mongodb
  apt:
    name: percona-server-mongodb
    state: present
    update_cache: yes
    install_recommends: no
    force_apt_get: yes