- name: Install percona mongodb
  include: install.yml
  tags: db

- name: Configure percona mongodb
  include: configure.yml
  tags: db

- name: Configure percona mongodb replica set
  include: replica.yml
  tags: db  