---
- name: restart cinder services on controller node(s)
  systemd:
    name: "{{ item }}"
    state: restarted
  register: service_restart
  until: service_restart|success
  retries: 5
  delay: 2
  with_items:
    - cinder-scheduler
  when: inventory_hostname in groups['controller']

- name: restart cinder services on storage node(s)
  systemd:
    name: "{{ item }}"
    state: restarted
  register: service_restart
  until: service_restart|success
  retries: 5
  delay: 2
  with_items:
    - cinder-volume
    - tgt
  when: inventory_hostname in groups['cinder_volume']

