---

#----------- ADD USER ------------
users:
  - name: tungdd5
    servers:
      # [fwork_redis]
      - 10.10.35.22	# Redis 1
      - 10.10.35.23	# Redis 2
      - 10.10.35.24	# Redis 3

    groups: sudo
    authorized_keys:
      - tungdd5.pub


      
#----------- REMOVE USER ------------
absent_users:
      #- hanhnn