---

- name: Create DB for service
  mysql_db:
    login_user: "{{ galera_root_user }}"
    login_password: "{{ galera_root_password }}"
    #login_host: "{{ glance_galera_address }}"
    name: "{{ glance_galera_database }}"
    state: "present"
  delegate_to: "{{ glance_db_setup_host }}"

- name: Grant access to the DB for the service
  mysql_user:
    login_user: "{{ galera_root_user }}"
    login_password: "{{ galera_root_password }}"
    #login_host: "{{ glance_galera_address }}"
    name: "{{ glance_galera_user }}"
    password: "{{ glance_user_password }}"
    host: "{{ item }}"  
    state: "present"
    priv: "{{ glance_galera_database }}.*:ALL"
  delegate_to: "{{ glance_db_setup_host }}"
  with_items:
    - "localhost"
    - "%"
    - "controller1"

- name: run keystone-db sync
  command: >
      glance-manage db_sync
  become: true
  become_user: glance
  run_once: true

