---
- name: Install glance yum packages
  package:
    name: "{{ item }}"
    state: latest
  register: packages_install
  until: packages_install is success
  retries: 5
  delay: 2
  with_items: "{{ glance_yum_packages }}"

- name: place `glance-registry.conf`
  template:
    src: "glance-registry.conf.j2"
    dest: "/etc/glance/glance-registry.conf"
    owner: "root"
    group: "{{ glance_default_system_group }}"
  notify:
    - Restart glance-registry
    
- name: place `glance-api.conf`
  template:
    src: "glance-api.conf.j2"
    dest: "/etc/glance/glance-api.conf"
    owner: "root"
    group: "{{ glance_default_system_group }}"
  notify:
    - Restart glance-api
