---
- name: list users
  shell: "source /root/admin-openrc &&  openstack service list"
  register: ulist
- name: setup service glance
  block:
    - raw: "source /root/admin-openrc && openstack user create --domain default --password {{ glance_user_password }} glance"
    - raw: "source /root/admin-openrc && openstack role add --project service --user glance admin"
    - raw: "source /root/admin-openrc && openstack service create --name glance --description 'OpenStack Image service' image"
    - raw: "source /root/admin-openrc && openstack endpoint create --region RegionOne image {{ item }} http://{{ internal_vip_address|default(groups['controller'][0]) }}:9292"
      with_items:
        - internal
        - public
        - admin
  when: ulist.stdout.find("glance") < 0

- name: start services
  systemd: name={{ item }} state=restarted enabled=yes
  when: not ansible_check_mode
  with_items:
    - openstack-glance-registry
    - openstack-glance-api



# - name: Add service to the keystone service catalog
#   os_keystone_service:
#     cloud: default
#     state: present
#     name: "{{ glance_service_name }}"
#     service_type: "{{ glance_service_type }}"
#     description: "{{ glance_service_description }}"
#     endpoint_type: admin
#     verify: "{{ not keystone_service_adminuri_insecure }}"
#   register: add_service
#   until: add_service is success
#   retries: 5
#   delay: 1

# - name: Add service user
#   os_user:
#     cloud: default
#     state: present
#     name: "{{ glance_service_user_name }}"
#     password: "{{ glance_service_password }}"
#     domain: default
#     default_project: "{{ glance_service_project_name }}"
#     endpoint_type: admin
#     verify: "{{ not keystone_service_adminuri_insecure }}"
#   register: add_service
#   until: add_service is success
#   retries: 5
#   delay: 10
# - name: Add service user to admin role
#   os_user_role:
#     cloud: default
#     state: present
#     user: "{{ glance_service_user_name }}"
#     role: "{{ glance_role_name }}"
#     project: "{{ glance_service_project_name }}"
#     endpoint_type: admin
#     verify: "{{ not keystone_service_adminuri_insecure }}"
#   register: add_service
#   until: add_service is success
#   retries: 5
#   delay: 1
# - name: Add endpoints to keystone endpoint catalog
#   os_keystone_endpoint:
#     cloud: default
#     state: present
#     service: "{{ glance_service_name }}"
#     endpoint_interface: "{{ item.interface }}"
#     url: "{{ item.url }}"
#     region: "{{ glance_service_region }}"
#     endpoint_type: admin
#     verify: "{{ not keystone_service_adminuri_insecure }}"
#   register: add_service
#   until: add_service is success
#   retries: 5
#   delay: 10
#   with_items:
#     - interface: "public"
#       url: "{{ glance_service_publicurl }}"
#     - interface: "internal"
#       url: "{{ glance_service_internalurl }}"
#     - interface: "admin"
#       url: "{{ glance_service_adminurl }}"