---
- name: restart nova controller services
  systemd:
    name: "{{ item }}"
    state: restarted
  with_items:
    - openstack-nova-api
    - openstack-nova-scheduler
    - openstack-nova-conductor
    - openstack-nova-novncproxy
    - openstac-nova-consoleauth
  when: inventory_hostname in groups['controller']

- name: restart nova compute service
  systemd:
    name: "openstack-nova-compute"
    state: restarted
  when: inventory_hostname in groups['compute']