---

galera_wsrep_cluster_address: "{% for host in groups['database'] %}{{ hostvars[host]['ansible_host'] }}{% if not loop.last %},{% endif %}{% endfor %}"
galera_server_bootstrap_node: "{{ groups['database'][0] }}"
galera_cluster_name: "openstack_database"
mariadb_root_password: 5bPcVNmwRw7dfcY5XZDH