---
- name: restart pushgateway
  become: true
  systemd:
    daemon_reload: true
    name: pushgateway
    state: restarted
    enabled: yes

- name: reload pushgateway
  become: true
  systemd:
    name: pushgateway
    state: reloaded