---

- name: Install git
  package:
    name: git
    state: present

- name: git clone letsencrypt/letsencrypt
  git: 
    repo: https://github.com/letsencrypt/letsencrypt 
    dest: /opt/letsencrypt/

- name: Install letsencrypt dependencies (takes a while)
  command: /opt/letsencrypt/letsencrypt-auto --help ## This is a bit stupid but it installs the deps without input.

- name: Create letsencrypt config file /opt/letsencrypt/cli.ini
  template: 
    src: cli.ini.j2
    dest: /opt/letsencrypt/cli.ini

- name: Get SSL certificate from letsencrypt
#  command: /opt/letsencrypt/letsencrypt-auto certonly -c /opt/letsencrypt/cli.ini --agree-tos
  command: /opt/letsencrypt/letsencrypt-auto certonly --dry-run --standalone -d {{ domain }}
  args:
    creates: /etc/letsencrypt/live/{{ domain }}/fullchain.pem