---

#=== Install MongoDB Standalone
# - name: Install percona-server-mongodb | Debian
#   include: install_debian.yml
#   when: ansible_os_family == 'Debian'

# - name: Install percona-server-mongodb | RedHat
#   include: install_redhat.yml
#   when: ansible_os_family == 'RedHat'

# - name: Tune MongoDB
#   include: tuning.yml


#=== Install MongoDB Replicaset_Run after Install MongoDB Standalone
# - name: Replicaset Config
#   include: replicaset.yml


#=== Add new Nodes
# - name: Add new Nodes
#   include: add_node.yml


#=== Add Arbiter node
- name: Add Arbiter node
  include: add_arbiter.yml
# them option chay sau khi job Replicaset Config done


#=== Uninstall MongoDB
# - name: Uninstall MongoDB
#   include: uninstall.yml