---
# handlers file for alertmanager
  - name: restart alertmanager
    systemd:
      name: alertmanager
      daemon_reload: true
      state: restarted
      enabled: yes
      
  - name: reload alertmanager
    systemd:
      name: alertmanager
      state: reloaded

