---
- hosts: 192.168.10.82
  tasks:
    - name: Ensure Service MariaDB Stoped
      service: 
        name: mariadb
        state: stopped

    - name: Remove MariaDB
      yum:
        name:
          - mariadb-server
          - mariadb
        state: absent

    - name: Delete directory /var/lib/mysql/
      file:
        path: "/var/lib/mysql/"
        state: absent

    - name: Delete directory /etc/my.cnf.d/
      file:
        path: "/etc/my.cnf.d/"
        state: absent