---

#=== Tanka
tanka_version: 0.12.0
tanka_url: https://github.com/grafana/tanka/releases/download/v{{ tanka_version }}/tk-linux-{{ go_arch }}


#=== Loki
loki_version: 2.0.0
loki_url: https://github.com/grafana/loki/releases/download/v{{ loki_version }}/loki-linux-{{ go_arch }}.zip   

#===> ansible_architecture
go_arch_map:
  i386: '386'
  x86_64: 'amd64'
  aarch64: 'arm64'
  armv7l: 'armv7'
  armv6l: 'armv6'

go_arch: "{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}"
#===> ansible_architecture