---
- include: setup-infra.yml
- include: setup-message-queue.yml
  #- include: setup-corosync-pacemaker.yml
- include: os-database.yml
  #- include: os-keystone-setup.yml
  #- include: os-glance-setup.yml
  #- include: os-nova-setup.yml
  #- include: os-neutron-setup.yaml
  #- include: os-cinder-setup.yml
  #- include: os-dashboard-setup.yml
