- name: Update redis config file
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis-server.conf
  tags: redis-config

- name: Be sure configure bind to interface
  lineinfile:
    path: /etc/redis/redis-server.conf
    regexp: '^bind'
    line: "bind 127.0.0.1 {{ ansible_all_ipv4_addresses | ipaddr('172.16.0.0/16') | first }}"
    backrefs: yes
  notify:
    - restart redis
  tags: redis-config